### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by tbarchyn** [IM3S/LDAR_Sim#13]
@KeeganShaw-GIS @tarcadius Soroush

Scheduled releases to the model in the public branch?

I'm keen to push all developments public as soon as possible - but there is an organizational issue whereby people coming by and cloning the code base will have all sorts of different versions of the model. Some of which might not work.

Rallying behind a release approach could focus energies on polishing something for public use - while maintaining freedom to explore research avenues in a development version of the code base.

Thoughts on this?

**Comment by tarcadius** [comment]
I totally agree. I think we need to have a conversation about this. @KeeganShaw-GIS  - can you add it to the next next agenda (next week's) so that Tom can be there? The first step is to clean things up in the public branch. The one downside that we should talk about is that a "release" risks letting other parties run away with divergent versions of the model if releases aren't released sufficiently frequently, right? Thinking of the HW repo here. Or if HW wants to propose changes, would it push them to IM3S as part of a future release? Having 3 repos is hard!

**Comment by KeeganShaw-GIS** [comment]
@tbarchyn. Also agree. We discussed this briefly last week I proposed using Git Issues/projects and milestones to define different versions. For instance, V2 could be released June 30th, and would include all new method modules / global parameters / and general code improvements.

**Comment by tarcadius** [comment]
@tbarchyn @KeeganShaw-GIS 
Is this issue closed?

**Comment by tbarchyn** [comment]
Sure
