### ISSUE TITLE
Minimum interval

### ISSUE THREAD

**Issue by tarcadius** [IM3S/LDAR_Sim#20]
Minimum interval is complex and causes problems. Always forget to change it. Doesn't guarantee work gets done.

Perhaps this will be resolved with Mo's scheduling.

Perhaps minimum interval should be calculated internally.

Perhaps minimum interval should just be a regulatory thing, but true scheduling is independent.

**Comment by tarcadius** [comment]
One way to possibly do this (pending scheduling) would be to have a "time between surveys" variable that would likely be a number of days or months... is this too easy/good to be true! @AkaMrmuffin @tbarchyn @KeeganShaw-GIS

**Comment by AkaMrmuffin** [comment]
I think we should keep "time between surveys." It actually represents a general scheduling time when there is no specific scheduling. One option to solve this issue is when scheduling is enabled, especially when specific survey time is required, such as "only fly aircraft at the July," then the "time between surveys" will be overwritten to 0 for each facility. Otherwise, use the "time between surveys".

**Comment by tarcadius** [comment]
What's the status on this @AkaMrmuffin and @KeeganShaw-GIS ? Is min_int only used if scheduling isn't used? Or is it used either way? My gut is to get rid of it and just calculate it automatically internally because I can't imagine a situation in which a technology with e.g., quarterly surveys would want to do them all in a month (it's just a bad idea). Should we get rid of this to simplify things - and allow people to schedule any way they want? Please discuss.

**Comment by AkaMrmuffin** [comment]
It is used either way. If the exact survey time interval is specified (e.g., only June 2018), they should be 0 for all facilities since min_int will stop technologies from visiting facilities. We can get rid of it, but when scheduling is not activated, the crew may visit some facilities too many times than other facilities since there is no enough rule to regulate their visiting order except the generated emission rate from the facility. I think this is part of the question: "how to represent the work practices when there are not enough data to define the real work practice." I am actually leaning to keep the min_int. We should discuss it this Friday.

**Comment by tarcadius** [comment]
@KeeganShaw-GIS  Can you please add this to the agenda for next week?

**Comment by AkaMrmuffin** [comment]
This is solved last week
